import dns.resolver
import asyncio
import httpx
import argparse
import os

# Ultra-extended fingerprints + A-record support
FINGERPRINTS = {
    "github": {"cname": ["github.io"], "sig": ["There isn't a GitHub Pages site here", "404 Not Found"]},
    "s3_bucket": {"cname": ["amazonaws.com", "s3.amazonaws.com"], "sig": ["The specified bucket does not exist", "NoSuchBucket"]},
    "cloudfront": {"cname": ["cloudfront.net"], "sig": ["Bad request", "Generated by cloudfront"]},
    "heroku": {"cname": ["herokudns.com", "herokuapp.com"], "sig": ["There's nothing here, yet"]},
    "azure": {"cname": ["azurewebsites.net", "cloudapp.net"], "sig": ["404 Web Site not found"]}
}

async def check_http(subdomain):
    """Probes the site. Returns service name if vulnerable sig is found."""
    async with httpx.AsyncClient(verify=False, timeout=7.0, follow_redirects=True) as client:
        for proto in ["http://", "https://"]:
            try:
                resp = await client.get(f"{proto}{subdomain}")
                for service, data in FINGERPRINTS.items():
                    if any(s.lower() in resp.text.lower() for s in data["sig"]):
                        return service
            except:
                continue
    return None

async def inspect_subdomain(subdomain, sem):
    async with sem:
        res = {"subdomain": subdomain, "status": "Clean", "details": ""}
        try:
            # TRY CNAME FIRST
            try:
                answers = dns.resolver.resolve(subdomain, 'CNAME')
                res["details"] = f"CNAME: {str(answers[0].target)}"
            except:
                # FALLBACK TO A RECORD (Some S3 buckets use A records)
                answers = dns.resolver.resolve(subdomain, 'A')
                res["details"] = f"A: {str(answers[0])}"

            # ACTIVE HTTP CHECK
            vuln_service = await check_http(subdomain)
            if vuln_service:
                res["status"] = "VULNERABLE"
                res["details"] = f"{vuln_service} | {res['details']}"
        except Exception as e:
            res["status"] = "DNS_ERROR"
        
        return res

async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-l", "--list", required=True)
    args = parser.parse_args()

    # Sanitized naming
    clean_name = os.path.basename(args.list).replace("/", "_")
    output_file = f"hits_{clean_name}"
    debug_file = f"scanned_{clean_name}"

    with open(args.list, "r") as f:
        subs = [l.strip() for l in f if l.strip()]

    sem = asyncio.Semaphore(50)
    tasks = [inspect_subdomain(s, sem) for s in subs]
    results = await asyncio.gather(*tasks)

    # WRITE HITS (The important stuff)
    with open(output_file, "w") as f_hits, open(debug_file, "w") as f_all:
        for r in results:
            log_line = f"{r['status']} | {r['subdomain']} | {r['details']}\n"
            f_all.write(log_line) # Logs everything so you know it ran
            if r["status"] == "VULNERABLE":
                f_hits.write(log_line)
                print(f"[!] POSITIVE TAKEOVER: {r['subdomain']}")

    print(f"\n[+] Total scanned: {len(results)}")
    print(f"[+] Hits saved to: {output_file}")
    print(f"[+] Full log saved to: {debug_file}")

if __name__ == "__main__":
    asyncio.run(main())
